# This file was generated by GoReleaser. DO NOT EDIT.
cask "serval" do
  desc ""
  homepage ""
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serval"

  on_macos do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.5.0/serval_Darwin_x86_64.tar.gz"
      sha256 "4f093fcf60b4e6a178e35c52bd66926fed975b8eae5598353e437cb87bd31df5"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.5.0/serval_Darwin_arm64.tar.gz"
      sha256 "2640ff3cf0680efd192b94273e11e308e09f91be710dc658f86693e37c87b9e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.5.0/serval_Linux_x86_64.tar.gz"
      sha256 "767d3ff505e9281798480fb56099467c8680686202d5938ca6f06ae3f20ceaa8"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.5.0/serval_Linux_arm64.tar.gz"
      sha256 "2a2a6356b42026a70a50d7ff090cd0e0e34216396b8cfb3838761fa92393e12e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/serval"]
    end
  end

  # No zap stanza required
end
