# This file was generated by GoReleaser. DO NOT EDIT.
cask "serval" do
  desc ""
  homepage ""
  version "0.2.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serval"

  on_macos do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.2.12/serval_Darwin_x86_64.tar.gz"
      sha256 "c660ac5a0d1bdbfd4d18fb74eb67c82b01d8fbc56381680ccbc119ff295c1abd"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.2.12/serval_Darwin_arm64.tar.gz"
      sha256 "97aa5d83ea8d0dac690e04c3dff072da81f6b2f777acb2a3f9cdbe7d45a78b75"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.2.12/serval_Linux_x86_64.tar.gz"
      sha256 "73b3c1cdb30d815d322a057f11b36abeaabc4b730267678d846e62e51ed4bcf3"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.2.12/serval_Linux_arm64.tar.gz"
      sha256 "63b64df5d526f87fa6aa68d7ec2bb0e30102996d20eeb99a8a56da6f922c98e6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/serval"]
    end
  end

  # No zap stanza required
end
