# This file was generated by GoReleaser. DO NOT EDIT.
cask "serval" do
  desc ""
  homepage ""
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serval"

  on_macos do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.4.0/serval_Darwin_x86_64.tar.gz"
      sha256 "4285d38b4558af02471257d44cf5252c811d3520b8dc6ded062fe0fb269f2d56"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.4.0/serval_Darwin_arm64.tar.gz"
      sha256 "285dd413e375a9cf6d5cd592779e541e6d85da9625dabce777a5ccbef7902b35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.4.0/serval_Linux_x86_64.tar.gz"
      sha256 "2e22490f1eff5a2ef35bba8d98174593133626fed9987f71f4b2af1d3816e697"
    end
    on_arm do
      url "https://github.com/ServalHQ/homebrew-serval/releases/download/v0.4.0/serval_Linux_arm64.tar.gz"
      sha256 "d3aad80a1d184a962e7d6e277934aafd54cb40e3f2aac1a068054736950f64d3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/serval"]
    end
  end

  # No zap stanza required
end
